// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls;
using System.Windows;

namespace ModernWpf.Controls.Primitives
{
    public partial class ColorPickerSlider
    {
        #region ColorChannel

        public static readonly DependencyProperty ColorChannelProperty =
            DependencyProperty.Register(
                nameof(ColorChannel),
                typeof(ColorPickerHsvChannel),
                typeof(ColorPickerSlider),
                new PropertyMetadata(ColorPickerHsvChannel.Value));

        public ColorPickerHsvChannel ColorChannel
        {
            get => (ColorPickerHsvChannel)GetValue(ColorChannelProperty);
            set => SetValue(ColorChannelProperty, value);
        }

        #endregion
    }
}
