// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls;
using System.Numerics;
using System.Windows;
using System.Windows.Media;

namespace ModernWpf.Controls.Primitives
{
    public partial class ColorSpectrum
    {
        #region Color

        public static readonly DependencyProperty ColorProperty =
            DependencyProperty.Register(
                nameof(Color),
                typeof(Color),
                typeof(ColorSpectrum),
                new PropertyMetadata(Colors.White, OnColorPropertyChanged));

        public Color Color
        {
            get => (Color)GetValue(ColorProperty);
            set => SetValue(ColorProperty, value);
        }

        #endregion

        #region HsvColor

        public static readonly DependencyProperty HsvColorProperty =
            DependencyProperty.Register(
                nameof(HsvColor),
                typeof(Vector4),
                typeof(ColorSpectrum),
                new PropertyMetadata(new Vector4(0, 0, 1, 1), OnHsvColorPropertyChanged));

        public Vector4 HsvColor
        {
            get => (Vector4)GetValue(HsvColorProperty);
            set => SetValue(HsvColorProperty, value);
        }

        #endregion

        #region MinHue

        public static readonly DependencyProperty MinHueProperty =
            DependencyProperty.Register(
                nameof(MinHue),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(0, OnHueRangePropertyChanged));

        public int MinHue
        {
            get => (int)GetValue(MinHueProperty);
            set => SetValue(MinHueProperty, value);
        }

        #endregion

        #region MaxHue

        public static readonly DependencyProperty MaxHueProperty =
            DependencyProperty.Register(
                nameof(MaxHue),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(359, OnHueRangePropertyChanged));

        public int MaxHue
        {
            get => (int)GetValue(MaxHueProperty);
            set => SetValue(MaxHueProperty, value);
        }

        #endregion

        #region MinSaturation

        public static readonly DependencyProperty MinSaturationProperty =
            DependencyProperty.Register(
                nameof(MinSaturation),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(0, OnSaturationRangePropertyChanged));

        public int MinSaturation
        {
            get => (int)GetValue(MinSaturationProperty);
            set => SetValue(MinSaturationProperty, value);
        }

        #endregion

        #region MaxSaturation

        public static readonly DependencyProperty MaxSaturationProperty =
            DependencyProperty.Register(
                nameof(MaxSaturation),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(100, OnSaturationRangePropertyChanged));

        public int MaxSaturation
        {
            get => (int)GetValue(MaxSaturationProperty);
            set => SetValue(MaxSaturationProperty, value);
        }

        #endregion

        #region MinValue

        public static readonly DependencyProperty MinValueProperty =
            DependencyProperty.Register(
                nameof(MinValue),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(0, OnValueRangePropertyChanged));

        public int MinValue
        {
            get => (int)GetValue(MinValueProperty);
            set => SetValue(MinValueProperty, value);
        }

        #endregion

        #region MaxValue

        public static readonly DependencyProperty MaxValueProperty =
            DependencyProperty.Register(
                nameof(MaxValue),
                typeof(int),
                typeof(ColorSpectrum),
                new PropertyMetadata(100, OnValueRangePropertyChanged));

        public int MaxValue
        {
            get => (int)GetValue(MaxValueProperty);
            set => SetValue(MaxValueProperty, value);
        }

        #endregion

        #region Shape

        public static readonly DependencyProperty ShapeProperty =
            DependencyProperty.Register(
                nameof(Shape),
                typeof(ColorSpectrumShape),
                typeof(ColorSpectrum),
                new PropertyMetadata(ColorSpectrumShape.Box, OnShapePropertyChanged));

        public ColorSpectrumShape Shape
        {
            get => (ColorSpectrumShape)GetValue(ShapeProperty);
            set => SetValue(ShapeProperty, value);
        }

        #endregion

        #region Components

        public static readonly DependencyProperty ComponentsProperty =
            DependencyProperty.Register(
                nameof(Components),
                typeof(ColorSpectrumComponents),
                typeof(ColorSpectrum),
                new PropertyMetadata(ColorSpectrumComponents.HueSaturation, OnComponentsPropertyChanged));

        public ColorSpectrumComponents Components
        {
            get => (ColorSpectrumComponents)GetValue(ComponentsProperty);
            set => SetValue(ComponentsProperty, value);
        }

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            System.Windows.Controls.Border.CornerRadiusProperty.AddOwner(typeof(ColorSpectrum));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion
    }
}
