// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace ModernWpf.Controls
{
    public partial class ColorPicker
    {
        #region Color

        public static readonly DependencyProperty ColorProperty =
            DependencyProperty.Register(
                nameof(Color),
                typeof(Color),
                typeof(ColorPicker),
                new PropertyMetadata(Colors.White, OnColorPropertyChanged));

        public Color Color
        {
            get => (Color)GetValue(ColorProperty);
            set => SetValue(ColorProperty, value);
        }

        #endregion

        #region PreviousColor

        public static readonly DependencyProperty PreviousColorProperty =
            DependencyProperty.Register(
                nameof(PreviousColor),
                typeof(Color?),
                typeof(ColorPicker),
                new PropertyMetadata(null, OnPreviousColorPropertyChanged));

        public Color? PreviousColor
        {
            get => (Color?)GetValue(PreviousColorProperty);
            set => SetValue(PreviousColorProperty, value);
        }

        #endregion

        #region IsAlphaEnabled

        public static readonly DependencyProperty IsAlphaEnabledProperty =
            DependencyProperty.Register(
                nameof(IsAlphaEnabled),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(false, OnIsAlphaEnabledPropertyChanged));

        public bool IsAlphaEnabled
        {
            get => (bool)GetValue(IsAlphaEnabledProperty);
            set => SetValue(IsAlphaEnabledProperty, value);
        }

        #endregion

        #region IsColorSpectrumVisible

        public static readonly DependencyProperty IsColorSpectrumVisibleProperty =
            DependencyProperty.Register(
                nameof(IsColorSpectrumVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsColorSpectrumVisible
        {
            get => (bool)GetValue(IsColorSpectrumVisibleProperty);
            set => SetValue(IsColorSpectrumVisibleProperty, value);
        }

        #endregion

        #region IsColorPreviewVisible

        public static readonly DependencyProperty IsColorPreviewVisibleProperty =
            DependencyProperty.Register(
                nameof(IsColorPreviewVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsColorPreviewVisible
        {
            get => (bool)GetValue(IsColorPreviewVisibleProperty);
            set => SetValue(IsColorPreviewVisibleProperty, value);
        }

        #endregion

        #region IsColorSliderVisible

        public static readonly DependencyProperty IsColorSliderVisibleProperty =
            DependencyProperty.Register(
                nameof(IsColorSliderVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsColorSliderVisible
        {
            get => (bool)GetValue(IsColorSliderVisibleProperty);
            set => SetValue(IsColorSliderVisibleProperty, value);
        }

        #endregion

        #region IsAlphaSliderVisible

        public static readonly DependencyProperty IsAlphaSliderVisibleProperty =
            DependencyProperty.Register(
                nameof(IsAlphaSliderVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsAlphaSliderVisible
        {
            get => (bool)GetValue(IsAlphaSliderVisibleProperty);
            set => SetValue(IsAlphaSliderVisibleProperty, value);
        }

        #endregion

        #region IsMoreButtonVisible

        public static readonly DependencyProperty IsMoreButtonVisibleProperty =
            DependencyProperty.Register(
                nameof(IsMoreButtonVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(false, OnPartVisibilityPropertyChanged));

        public bool IsMoreButtonVisible
        {
            get => (bool)GetValue(IsMoreButtonVisibleProperty);
            set => SetValue(IsMoreButtonVisibleProperty, value);
        }

        #endregion

        #region IsColorChannelTextInputVisible

        public static readonly DependencyProperty IsColorChannelTextInputVisibleProperty =
            DependencyProperty.Register(
                nameof(IsColorChannelTextInputVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsColorChannelTextInputVisible
        {
            get => (bool)GetValue(IsColorChannelTextInputVisibleProperty);
            set => SetValue(IsColorChannelTextInputVisibleProperty, value);
        }

        #endregion

        #region IsAlphaTextInputVisible

        public static readonly DependencyProperty IsAlphaTextInputVisibleProperty =
            DependencyProperty.Register(
                nameof(IsAlphaTextInputVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsAlphaTextInputVisible
        {
            get => (bool)GetValue(IsAlphaTextInputVisibleProperty);
            set => SetValue(IsAlphaTextInputVisibleProperty, value);
        }

        #endregion

        #region IsHexInputVisible

        public static readonly DependencyProperty IsHexInputVisibleProperty =
            DependencyProperty.Register(
                nameof(IsHexInputVisible),
                typeof(bool),
                typeof(ColorPicker),
                new PropertyMetadata(true, OnPartVisibilityPropertyChanged));

        public bool IsHexInputVisible
        {
            get => (bool)GetValue(IsHexInputVisibleProperty);
            set => SetValue(IsHexInputVisibleProperty, value);
        }

        #endregion

        #region MinHue

        public static readonly DependencyProperty MinHueProperty =
            DependencyProperty.Register(
                nameof(MinHue),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(0, OnMinMaxHuePropertyChanged));

        public int MinHue
        {
            get => (int)GetValue(MinHueProperty);
            set => SetValue(MinHueProperty, value);
        }

        #endregion

        #region MaxHue

        public static readonly DependencyProperty MaxHueProperty =
            DependencyProperty.Register(
                nameof(MaxHue),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(359, OnMinMaxHuePropertyChanged));

        public int MaxHue
        {
            get => (int)GetValue(MaxHueProperty);
            set => SetValue(MaxHueProperty, value);
        }

        #endregion

        #region MinSaturation

        public static readonly DependencyProperty MinSaturationProperty =
            DependencyProperty.Register(
                nameof(MinSaturation),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(0, OnMinMaxSaturationPropertyChanged));

        public int MinSaturation
        {
            get => (int)GetValue(MinSaturationProperty);
            set => SetValue(MinSaturationProperty, value);
        }

        #endregion

        #region MaxSaturation

        public static readonly DependencyProperty MaxSaturationProperty =
            DependencyProperty.Register(
                nameof(MaxSaturation),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(100, OnMinMaxSaturationPropertyChanged));

        public int MaxSaturation
        {
            get => (int)GetValue(MaxSaturationProperty);
            set => SetValue(MaxSaturationProperty, value);
        }

        #endregion

        #region MinValue

        public static readonly DependencyProperty MinValueProperty =
            DependencyProperty.Register(
                nameof(MinValue),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(0, OnMinMaxValuePropertyChanged));

        public int MinValue
        {
            get => (int)GetValue(MinValueProperty);
            set => SetValue(MinValueProperty, value);
        }

        #endregion

        #region MaxValue

        public static readonly DependencyProperty MaxValueProperty =
            DependencyProperty.Register(
                nameof(MaxValue),
                typeof(int),
                typeof(ColorPicker),
                new PropertyMetadata(100, OnMinMaxValuePropertyChanged));

        public int MaxValue
        {
            get => (int)GetValue(MaxValueProperty);
            set => SetValue(MaxValueProperty, value);
        }

        #endregion

        #region ColorSpectrumShape

        public static readonly DependencyProperty ColorSpectrumShapeProperty =
            DependencyProperty.Register(
                nameof(ColorSpectrumShape),
                typeof(ColorSpectrumShape),
                typeof(ColorPicker),
                new PropertyMetadata(ColorSpectrumShape.Box, OnColorSpectrumShapePropertyChanged));

        public ColorSpectrumShape ColorSpectrumShape
        {
            get => (ColorSpectrumShape)GetValue(ColorSpectrumShapeProperty);
            set => SetValue(ColorSpectrumShapeProperty, value);
        }

        #endregion

        #region ColorSpectrumComponents

        public static readonly DependencyProperty ColorSpectrumComponentsProperty =
            DependencyProperty.Register(
                nameof(ColorSpectrumComponents),
                typeof(ColorSpectrumComponents),
                typeof(ColorPicker),
                new PropertyMetadata(ColorSpectrumComponents.HueSaturation, OnColorSpectrumComponentsPropertyChanged));

        public ColorSpectrumComponents ColorSpectrumComponents
        {
            get => (ColorSpectrumComponents)GetValue(ColorSpectrumComponentsProperty);
            set => SetValue(ColorSpectrumComponentsProperty, value);
        }

        #endregion

        #region Orientation

        public static readonly DependencyProperty OrientationProperty =
            DependencyProperty.Register(
                nameof(Orientation),
                typeof(Orientation),
                typeof(ColorPicker),
                new PropertyMetadata(Orientation.Vertical, OnOrientationPropertyChanged));

        public Orientation Orientation
        {
            get => (Orientation)GetValue(OrientationProperty);
            set => SetValue(OrientationProperty, value);
        }

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            ControlHelper.CornerRadiusProperty.AddOwner(typeof(ColorPicker));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion
    }
}
