// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using System.Windows;

namespace ModernWpf.Controls
{
    public static partial class ContextFlyoutService
    {
        #region ContextFlyout

        public static readonly DependencyProperty ContextFlyoutProperty =
            DependencyProperty.RegisterAttached(
                "ContextFlyout",
                typeof(FlyoutBase),
                typeof(ContextFlyoutService),
                new PropertyMetadata(OnContextFlyoutChanged));

        #endregion
    }
}
