// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using System.Windows;

namespace ModernWpf.Controls
{
    public static partial class FlyoutService
    {
        #region Flyout

        public static readonly DependencyProperty FlyoutProperty =
            DependencyProperty.RegisterAttached(
                "Flyout",
                typeof(FlyoutBase),
                typeof(FlyoutService),
                new PropertyMetadata(OnFlyoutChanged));

        #endregion
    }
}
