version: 2
updates:
  - package-ecosystem: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: "/"
    schedule:
      interval: "daily"

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)