// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public sealed partial class InfoBadgeTemplateSettings
    {
        #region InfoBadgeCornerRadius

        public static readonly DependencyProperty InfoBadgeCornerRadiusProperty =
            DependencyProperty.Register(
                nameof(InfoBadgeCornerRadius),
                typeof(CornerRadius),
                typeof(InfoBadgeTemplateSettings),
                null);

        public CornerRadius InfoBadgeCornerRadius
        {
            get => (CornerRadius)GetValue(InfoBadgeCornerRadiusProperty);
            internal set => SetValue(InfoBadgeCornerRadiusProperty, value);
        }

        #endregion

        #region IconElement

        public static readonly DependencyProperty IconElementProperty =
            DependencyProperty.Register(
                nameof(IconElement),
                typeof(IconElement),
                typeof(InfoBadgeTemplateSettings),
                null);

        public IconElement IconElement
        {
            get => (IconElement)GetValue(IconElementProperty);
            internal set => SetValue(IconElementProperty, value);
        }

        #endregion
    }
}
