// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class RecyclePool
    {
        #region ReuseKey

        internal static readonly DependencyProperty ReuseKeyProperty =
            DependencyProperty.RegisterAttached(
                "ReuseKey",
                typeof(string),
                typeof(RecyclePool),
                new PropertyMetadata(string.Empty));

        #endregion

        #region OriginTemplate

        internal static readonly DependencyProperty OriginTemplateProperty =
            DependencyProperty.RegisterAttached(
                "OriginTemplate",
                typeof(DataTemplate),
                typeof(RecyclePool),
                null);

        #endregion
    }
}
