<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\**" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fluent.Ribbon" Version="11.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ModernWpf.Controls\ModernWpf.Controls.csproj" />
    <ProjectReference Include="..\..\ModernWpf\ModernWpf.csproj" />
    <ProjectReference Include="..\SamplesCommon\SamplesCommon.csproj" />
  </ItemGroup>

</Project>
