// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class MenuFlyout
    {
        #region MenuFlyoutPresenterStyle

        public static readonly DependencyProperty MenuFlyoutPresenterStyleProperty =
            DependencyProperty.Register(
                nameof(MenuFlyoutPresenterStyle),
                typeof(Style),
                typeof(MenuFlyout),
                new PropertyMetadata(OnMenuFlyoutPresenterStyleChanged));

        public Style MenuFlyoutPresenterStyle
        {
            get => (Style)GetValue(MenuFlyoutPresenterStyleProperty);
            set => SetValue(MenuFlyoutPresenterStyleProperty, value);
        }

        #endregion
    }
}
