// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class StackLayout
    {
        #region DisableVirtualization

        public static readonly DependencyProperty DisableVirtualizationProperty =
            DependencyProperty.Register(
                nameof(DisableVirtualization),
                typeof(bool),
                typeof(StackLayout),
                new PropertyMetadata(false, OnPropertyChanged));

        #endregion

        #region IsVirtualizationEnabled

        public static readonly DependencyProperty IsVirtualizationEnabledProperty =
            DependencyProperty.Register(
                nameof(IsVirtualizationEnabled),
                typeof(bool),
                typeof(StackLayout),
                new PropertyMetadata(true, OnPropertyChanged));

        public bool IsVirtualizationEnabled
        {
            get => (bool)GetValue(IsVirtualizationEnabledProperty);
            set => SetValue(IsVirtualizationEnabledProperty, value);
        }

        #endregion

        #region Orientation

        public static readonly DependencyProperty OrientationProperty =
            DependencyProperty.Register(
                nameof(Orientation),
                typeof(Orientation),
                typeof(StackLayout),
                new PropertyMetadata(Orientation.Vertical, OnPropertyChanged));

        public Orientation Orientation
        {
            get => (Orientation)GetValue(OrientationProperty);
            set => SetValue(OrientationProperty, value);
        }

        #endregion

        #region Spacing

        public static readonly DependencyProperty SpacingProperty =
            DependencyProperty.Register(
                nameof(Spacing),
                typeof(double),
                typeof(StackLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double Spacing
        {
            get => (double)GetValue(SpacingProperty);
            set => SetValue(SpacingProperty, value);
        }

        #endregion
    }
}
