//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernWpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string AppBarMoreButtonClosedToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More app bar.
        /// </summary>
        internal static string AppBarMoreButtonName {
            get {
                return ResourceManager.GetString("AppBarMoreButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See less.
        /// </summary>
        internal static string AppBarMoreButtonOpenToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, icon.
        /// </summary>
        internal static string BadgeIcon {
            get {
                return ResourceManager.GetString("BadgeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string BadgeIconTextOverride {
            get {
                return ResourceManager.GetString("BadgeIconTextOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural1 {
            get {
                return ResourceManager.GetString("BadgeItemPlural1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural2 {
            get {
                return ResourceManager.GetString("BadgeItemPlural2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural3 {
            get {
                return ResourceManager.GetString("BadgeItemPlural3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural4 {
            get {
                return ResourceManager.GetString("BadgeItemPlural4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural5 {
            get {
                return ResourceManager.GetString("BadgeItemPlural5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural6 {
            get {
                return ResourceManager.GetString("BadgeItemPlural6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} items.
        /// </summary>
        internal static string BadgeItemPlural7 {
            get {
                return ResourceManager.GetString("BadgeItemPlural7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} item.
        /// </summary>
        internal static string BadgeItemSingular {
            get {
                return ResourceManager.GetString("BadgeItemSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1:d} {2}.
        /// </summary>
        internal static string BadgeItemTextOverride {
            get {
                return ResourceManager.GetString("BadgeItemTextOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating, {0} of {1}.
        /// </summary>
        internal static string BasicRatingString {
            get {
                return ResourceManager.GetString("BasicRatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Rating, {0} of {1}.
        /// </summary>
        internal static string CommunityRatingString {
            get {
                return ResourceManager.GetString("CommunityRatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreMenuItemLabel {
            get {
                return ResourceManager.GetString("IgnoreMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NavigationBackButtonName {
            get {
                return ResourceManager.GetString("NavigationBackButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NavigationBackButtonToolTip {
            get {
                return ResourceManager.GetString("NavigationBackButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Navigation.
        /// </summary>
        internal static string NavigationButtonClosedName {
            get {
                return ResourceManager.GetString("NavigationButtonClosedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Navigation.
        /// </summary>
        internal static string NavigationButtonOpenName {
            get {
                return ResourceManager.GetString("NavigationButtonOpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NavigationCloseButtonName {
            get {
                return ResourceManager.GetString("NavigationCloseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string NavigationOverflowButtonName {
            get {
                return ResourceManager.GetString("NavigationOverflowButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string NavigationOverflowButtonText {
            get {
                return ResourceManager.GetString("NavigationOverflowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string NavigationOverflowButtonToolTip {
            get {
                return ResourceManager.GetString("NavigationOverflowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationViewItem.
        /// </summary>
        internal static string NavigationViewItemDefaultControlName {
            get {
                return ResourceManager.GetString("NavigationViewItemDefaultControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search.
        /// </summary>
        internal static string NavigationViewSearchButtonName {
            get {
                return ResourceManager.GetString("NavigationViewSearchButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string NumberBoxDownSpinButtonName {
            get {
                return ResourceManager.GetString("NumberBoxDownSpinButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string NumberBoxUpSpinButtonName {
            get {
                return ResourceManager.GetString("NumberBoxUpSpinButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ProgressBarErrorStatus {
            get {
                return ResourceManager.GetString("ProgressBarErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string ProgressBarIndeterminateStatus {
            get {
                return ResourceManager.GetString("ProgressBarIndeterminateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string ProgressBarPausedStatus {
            get {
                return ResourceManager.GetString("ProgressBarPausedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string ProgressRingIndeterminateStatus {
            get {
                return ResourceManager.GetString("ProgressRingIndeterminateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofing.
        /// </summary>
        internal static string ProofingMenuItemLabel {
            get {
                return ResourceManager.GetString("ProofingMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RatingControlName {
            get {
                return ResourceManager.GetString("RatingControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Slider.
        /// </summary>
        internal static string RatingLocalizedControlType {
            get {
                return ResourceManager.GetString("RatingLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RatingsControlName {
            get {
                return ResourceManager.GetString("RatingsControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Unset.
        /// </summary>
        internal static string RatingUnset {
            get {
                return ResourceManager.GetString("RatingUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButtonName {
            get {
                return ResourceManager.GetString("SettingsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        internal static string SplitButtonSecondaryButtonName {
            get {
                return ResourceManager.GetString("SplitButtonSecondaryButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCommandLabelCopy {
            get {
                return ResourceManager.GetString("TextCommandLabelCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string TextCommandLabelCut {
            get {
                return ResourceManager.GetString("TextCommandLabelCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TextCommandLabelPaste {
            get {
                return ResourceManager.GetString("TextCommandLabelPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string TextCommandLabelRedo {
            get {
                return ResourceManager.GetString("TextCommandLabelRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string TextCommandLabelSelectAll {
            get {
                return ResourceManager.GetString("TextCommandLabelSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string TextCommandLabelUndo {
            get {
                return ResourceManager.GetString("TextCommandLabelUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
    }
}
