//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernWpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string AppBarMoreButtonClosedToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonClosedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More app bar.
        /// </summary>
        internal static string AppBarMoreButtonName {
            get {
                return ResourceManager.GetString("AppBarMoreButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See less.
        /// </summary>
        internal static string AppBarMoreButtonOpenToolTip {
            get {
                return ResourceManager.GetString("AppBarMoreButtonOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreMenuItemLabel {
            get {
                return ResourceManager.GetString("IgnoreMenuItemLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string InfoBarCloseButtonName {
            get {
                return ResourceManager.GetString("InfoBarCloseButtonName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string InfoBarCloseButtonTooltip {
            get {
                return ResourceManager.GetString("InfoBarCloseButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InfoBar dismissed.
        /// </summary>
        internal static string InfoBarClosedNotification {
            get {
                return ResourceManager.GetString("InfoBarClosedNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InfoBar.
        /// </summary>
        internal static string InfoBarCustomLandmarkName {
            get {
                return ResourceManager.GetString("InfoBarCustomLandmarkName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error icon.
        /// </summary>
        internal static string InfoBarIconSeverityErrorName {
            get {
                return ResourceManager.GetString("InfoBarIconSeverityErrorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informational icon.
        /// </summary>
        internal static string InfoBarIconSeverityInformationalName {
            get {
                return ResourceManager.GetString("InfoBarIconSeverityInformationalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success icon.
        /// </summary>
        internal static string InfoBarIconSeveritySuccessName {
            get {
                return ResourceManager.GetString("InfoBarIconSeveritySuccessName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning icon.
        /// </summary>
        internal static string InfoBarIconSeverityWarningName {
            get {
                return ResourceManager.GetString("InfoBarIconSeverityWarningName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string InfoBarOpenedNotification {
            get {
                return ResourceManager.GetString("InfoBarOpenedNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info message, severity error.
        /// </summary>
        internal static string InfoBarSeverityErrorName {
            get {
                return ResourceManager.GetString("InfoBarSeverityErrorName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info message, severity informational.
        /// </summary>
        internal static string InfoBarSeverityInformationalName {
            get {
                return ResourceManager.GetString("InfoBarSeverityInformationalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info message, severity success.
        /// </summary>
        internal static string InfoBarSeveritySuccessName {
            get {
                return ResourceManager.GetString("InfoBarSeveritySuccessName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info message, severity warning.
        /// </summary>
        internal static string InfoBarSeverityWarningName {
            get {
                return ResourceManager.GetString("InfoBarSeverityWarningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
    }
}
