// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class RadioMenuItem
    {
        #region GroupName

        public static readonly DependencyProperty GroupNameProperty =
            DependencyProperty.Register(
                nameof(GroupName),
                typeof(string),
                typeof(RadioMenuItem),
                new FrameworkPropertyMetadata(string.Empty, OnGroupNameChanged));

        public string GroupName
        {
            get => (string)GetValue(GroupNameProperty);
            set => SetValue(GroupNameProperty, value);
        }

        #endregion

        #region UseSystemFocusVisuals

        public static readonly DependencyProperty UseSystemFocusVisualsProperty =
            FocusVisualHelper.UseSystemFocusVisualsProperty.AddOwner(typeof(RadioMenuItem));

        public bool UseSystemFocusVisuals
        {
            get => (bool)GetValue(UseSystemFocusVisualsProperty);
            set => SetValue(UseSystemFocusVisualsProperty, value);
        }

        #endregion

        #region AreCheckStatesEnabled

        public static readonly DependencyProperty AreCheckStatesEnabledProperty =
            DependencyProperty.RegisterAttached(
                "AreCheckStatesEnabled",
                typeof(bool),
                typeof(RadioMenuItem),
                new PropertyMetadata(false, OnAreCheckStatesEnabledChanged));

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            System.Windows.Controls.Border.CornerRadiusProperty.AddOwner(typeof(RadioMenuItem));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion

        #region HookedRadioItems

        private static readonly DependencyProperty HookedRadioItemsProperty =
            DependencyProperty.RegisterAttached(
                "HookedRadioItems",
                typeof(List<RadioMenuItem>),
                typeof(RadioMenuItem),
                new PropertyMetadata(null));

        #endregion

        #region CollectionChangedHandler

        private static readonly DependencyProperty CollectionChangedHandlerProperty =
            DependencyProperty.RegisterAttached(
                "CollectionChangedHandler",
                typeof(NotifyCollectionChangedEventHandler),
                typeof(RadioMenuItem),
                new PropertyMetadata(null));

        #endregion
    }
}
