// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class ItemsRepeater
    {
        #region ItemsSource

        public static readonly DependencyProperty ItemsSourceProperty =
            DependencyProperty.Register(
                nameof(ItemsSource),
                typeof(object),
                typeof(ItemsRepeater),
                new PropertyMetadata(OnPropertyChanged));

        public object ItemsSource
        {
            get => (object)GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }

        #endregion

        #region ItemTemplate

        public static readonly DependencyProperty ItemTemplateProperty =
            DependencyProperty.Register(
                nameof(ItemTemplate),
                typeof(object),
                typeof(ItemsRepeater),
                new PropertyMetadata(OnPropertyChanged));

        public object ItemTemplate
        {
            get => (object)GetValue(ItemTemplateProperty);
            set => SetValue(ItemTemplateProperty, value);
        }

        #endregion

        #region Layout

        public static readonly DependencyProperty LayoutProperty =
            DependencyProperty.Register(
                nameof(Layout),
                typeof(Layout),
                typeof(ItemsRepeater),
                new PropertyMetadata(OnPropertyChanged));

        public Layout Layout
        {
            get => (Layout)GetValue(LayoutProperty);
            set => SetValue(LayoutProperty, value);
        }

        #endregion

        #region ItemTransitionProvider

        public static readonly DependencyProperty ItemTransitionProviderProperty =
            DependencyProperty.Register(
                nameof(ItemTransitionProvider),
                typeof(ItemCollectionTransitionProvider),
                typeof(ItemsRepeater),
                new PropertyMetadata(OnPropertyChanged));

        public ItemCollectionTransitionProvider ItemTransitionProvider
        {
            get => (ItemCollectionTransitionProvider)GetValue(ItemTransitionProviderProperty);
            set => SetValue(ItemTransitionProviderProperty, value);
        }

        #endregion

        #region Animator

        public static readonly DependencyProperty AnimatorProperty =
            DependencyProperty.Register(
                nameof(Animator),
                typeof(ElementAnimator),
                typeof(ItemsRepeater),
                new PropertyMetadata(OnPropertyChanged));

        internal ElementAnimator Animator
        {
            get => (ElementAnimator)GetValue(AnimatorProperty);
            set => SetValue(AnimatorProperty, value);
        }

        #endregion

        #region HorizontalCacheLength

        public static readonly DependencyProperty HorizontalCacheLengthProperty =
            DependencyProperty.Register(
                nameof(HorizontalCacheLength),
                typeof(double),
                typeof(ItemsRepeater),
                new PropertyMetadata(2.0, OnPropertyChanged));

        public double HorizontalCacheLength
        {
            get => (double)GetValue(HorizontalCacheLengthProperty);
            set => SetValue(HorizontalCacheLengthProperty, value);
        }

        #endregion

        #region VerticalCacheLength

        public static readonly DependencyProperty VerticalCacheLengthProperty =
            DependencyProperty.Register(
                nameof(VerticalCacheLength),
                typeof(double),
                typeof(ItemsRepeater),
                new PropertyMetadata(2.0, OnPropertyChanged));

        public double VerticalCacheLength
        {
            get => (double)GetValue(VerticalCacheLengthProperty);
            set => SetValue(VerticalCacheLengthProperty, value);
        }

        #endregion

        #region VirtualizationInfo

        internal static readonly DependencyProperty VirtualizationInfoProperty =
            DependencyProperty.RegisterAttached(
                "VirtualizationInfo",
                typeof(VirtualizationInfo),
                typeof(ItemsRepeater),
                null);

        #endregion
    }
}
