// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class ParallaxView
    {
        #region Child

        public static readonly DependencyProperty ChildProperty =
            DependencyProperty.Register(
                nameof(Child),
                typeof(UIElement),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.AffectsMeasure | FrameworkPropertyMetadataOptions.AffectsArrange, OnChildPropertyChanged));

        public new UIElement Child
        {
            get => (UIElement)GetValue(ChildProperty);
            set => SetValue(ChildProperty, value);
        }

        #endregion

        #region HorizontalShift

        public static readonly DependencyProperty HorizontalShiftProperty =
            DependencyProperty.Register(
                nameof(HorizontalShift),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsMeasure | FrameworkPropertyMetadataOptions.AffectsArrange));

        public double HorizontalShift
        {
            get => (double)GetValue(HorizontalShiftProperty);
            set => SetValue(HorizontalShiftProperty, value);
        }

        #endregion

        #region HorizontalSourceEndOffset

        public static readonly DependencyProperty HorizontalSourceEndOffsetProperty =
            DependencyProperty.Register(
                nameof(HorizontalSourceEndOffset),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double HorizontalSourceEndOffset
        {
            get => (double)GetValue(HorizontalSourceEndOffsetProperty);
            set => SetValue(HorizontalSourceEndOffsetProperty, value);
        }

        #endregion

        #region HorizontalSourceOffsetKind

        public static readonly DependencyProperty HorizontalSourceOffsetKindProperty =
            DependencyProperty.Register(
                nameof(HorizontalSourceOffsetKind),
                typeof(ParallaxSourceOffsetKind),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(ParallaxSourceOffsetKind.Relative, FrameworkPropertyMetadataOptions.AffectsArrange));

        public ParallaxSourceOffsetKind HorizontalSourceOffsetKind
        {
            get => (ParallaxSourceOffsetKind)GetValue(HorizontalSourceOffsetKindProperty);
            set => SetValue(HorizontalSourceOffsetKindProperty, value);
        }

        #endregion

        #region HorizontalSourceStartOffset

        public static readonly DependencyProperty HorizontalSourceStartOffsetProperty =
            DependencyProperty.Register(
                nameof(HorizontalSourceStartOffset),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double HorizontalSourceStartOffset
        {
            get => (double)GetValue(HorizontalSourceStartOffsetProperty);
            set => SetValue(HorizontalSourceStartOffsetProperty, value);
        }

        #endregion

        #region IsHorizontalShiftClamped

        public static readonly DependencyProperty IsHorizontalShiftClampedProperty =
            DependencyProperty.Register(
                nameof(IsHorizontalShiftClamped),
                typeof(bool),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(true, FrameworkPropertyMetadataOptions.AffectsArrange));

        public bool IsHorizontalShiftClamped
        {
            get => (bool)GetValue(IsHorizontalShiftClampedProperty);
            set => SetValue(IsHorizontalShiftClampedProperty, value);
        }

        #endregion

        #region IsVerticalShiftClamped

        public static readonly DependencyProperty IsVerticalShiftClampedProperty =
            DependencyProperty.Register(
                nameof(IsVerticalShiftClamped),
                typeof(bool),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(true, FrameworkPropertyMetadataOptions.AffectsArrange));

        public bool IsVerticalShiftClamped
        {
            get => (bool)GetValue(IsVerticalShiftClampedProperty);
            set => SetValue(IsVerticalShiftClampedProperty, value);
        }

        #endregion

        #region MaxHorizontalShiftRatio

        public static readonly DependencyProperty MaxHorizontalShiftRatioProperty =
            DependencyProperty.Register(
                nameof(MaxHorizontalShiftRatio),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(1.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double MaxHorizontalShiftRatio
        {
            get => (double)GetValue(MaxHorizontalShiftRatioProperty);
            set => SetValue(MaxHorizontalShiftRatioProperty, value);
        }

        #endregion

        #region MaxVerticalShiftRatio

        public static readonly DependencyProperty MaxVerticalShiftRatioProperty =
            DependencyProperty.Register(
                nameof(MaxVerticalShiftRatio),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(1.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double MaxVerticalShiftRatio
        {
            get => (double)GetValue(MaxVerticalShiftRatioProperty);
            set => SetValue(MaxVerticalShiftRatioProperty, value);
        }

        #endregion

        #region Source

        public static readonly DependencyProperty SourceProperty =
            DependencyProperty.Register(
                nameof(Source),
                typeof(UIElement),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(null, OnSourcePropertyChanged));

        public UIElement Source
        {
            get => (UIElement)GetValue(SourceProperty);
            set => SetValue(SourceProperty, value);
        }

        #endregion

        #region VerticalShift

        public static readonly DependencyProperty VerticalShiftProperty =
            DependencyProperty.Register(
                nameof(VerticalShift),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsMeasure | FrameworkPropertyMetadataOptions.AffectsArrange));

        public double VerticalShift
        {
            get => (double)GetValue(VerticalShiftProperty);
            set => SetValue(VerticalShiftProperty, value);
        }

        #endregion

        #region VerticalSourceEndOffset

        public static readonly DependencyProperty VerticalSourceEndOffsetProperty =
            DependencyProperty.Register(
                nameof(VerticalSourceEndOffset),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double VerticalSourceEndOffset
        {
            get => (double)GetValue(VerticalSourceEndOffsetProperty);
            set => SetValue(VerticalSourceEndOffsetProperty, value);
        }

        #endregion

        #region VerticalSourceOffsetKind

        public static readonly DependencyProperty VerticalSourceOffsetKindProperty =
            DependencyProperty.Register(
                nameof(VerticalSourceOffsetKind),
                typeof(ParallaxSourceOffsetKind),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(ParallaxSourceOffsetKind.Relative, FrameworkPropertyMetadataOptions.AffectsArrange));

        public ParallaxSourceOffsetKind VerticalSourceOffsetKind
        {
            get => (ParallaxSourceOffsetKind)GetValue(VerticalSourceOffsetKindProperty);
            set => SetValue(VerticalSourceOffsetKindProperty, value);
        }

        #endregion

        #region VerticalSourceStartOffset

        public static readonly DependencyProperty VerticalSourceStartOffsetProperty =
            DependencyProperty.Register(
                nameof(VerticalSourceStartOffset),
                typeof(double),
                typeof(ParallaxView),
                new FrameworkPropertyMetadata(0.0, FrameworkPropertyMetadataOptions.AffectsArrange));

        public double VerticalSourceStartOffset
        {
            get => (double)GetValue(VerticalSourceStartOffsetProperty);
            set => SetValue(VerticalSourceStartOffsetProperty, value);
        }

        #endregion
    }
}
