// Copyright (c) Kinnara. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class LinedFlowLayout
    {
        public static readonly DependencyProperty ItemsJustificationProperty =
            DependencyProperty.Register(
                nameof(ItemsJustification),
                typeof(LinedFlowLayoutItemsJustification),
                typeof(LinedFlowLayout),
                new PropertyMetadata(LinedFlowLayoutItemsJustification.Start, OnPropertyChanged));

        public LinedFlowLayoutItemsJustification ItemsJustification
        {
            get => (LinedFlowLayoutItemsJustification)GetValue(ItemsJustificationProperty);
            set => SetValue(ItemsJustificationProperty, value);
        }

        public static readonly DependencyProperty ItemsStretchProperty =
            DependencyProperty.Register(
                nameof(ItemsStretch),
                typeof(LinedFlowLayoutItemsStretch),
                typeof(LinedFlowLayout),
                new PropertyMetadata(LinedFlowLayoutItemsStretch.None, OnPropertyChanged));

        public LinedFlowLayoutItemsStretch ItemsStretch
        {
            get => (LinedFlowLayoutItemsStretch)GetValue(ItemsStretchProperty);
            set => SetValue(ItemsStretchProperty, value);
        }

        public static readonly DependencyProperty MinItemSpacingProperty =
            DependencyProperty.Register(
                nameof(MinItemSpacing),
                typeof(double),
                typeof(LinedFlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double MinItemSpacing
        {
            get => (double)GetValue(MinItemSpacingProperty);
            set => SetValue(MinItemSpacingProperty, value);
        }

        public static readonly DependencyProperty LineSpacingProperty =
            DependencyProperty.Register(
                nameof(LineSpacing),
                typeof(double),
                typeof(LinedFlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double LineSpacing
        {
            get => (double)GetValue(LineSpacingProperty);
            set => SetValue(LineSpacingProperty, value);
        }

        public static readonly DependencyProperty LineHeightProperty =
            DependencyProperty.Register(
                nameof(LineHeight),
                typeof(double),
                typeof(LinedFlowLayout),
                new PropertyMetadata(double.NaN, OnPropertyChanged));

        public double LineHeight
        {
            get => (double)GetValue(LineHeightProperty);
            set => SetValue(LineHeightProperty, value);
        }

        private static readonly DependencyPropertyKey ActualLineHeightPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(ActualLineHeight),
                typeof(double),
                typeof(LinedFlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public static readonly DependencyProperty ActualLineHeightProperty =
            ActualLineHeightPropertyKey.DependencyProperty;

        public double ActualLineHeight => (double)GetValue(ActualLineHeightProperty);

        private void SetActualLineHeight(double value)
        {
            SetValue(ActualLineHeightPropertyKey, value);
        }
    }
}
