// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class AnnotatedScrollBar
    {
        #region Labels

        public static readonly DependencyProperty LabelsProperty =
            DependencyProperty.Register(
                nameof(Labels),
                typeof(IList<AnnotatedScrollBarLabel>),
                typeof(AnnotatedScrollBar),
                new FrameworkPropertyMetadata(null, OnLabelsPropertyChanged));

        public IList<AnnotatedScrollBarLabel> Labels
        {
            get => (IList<AnnotatedScrollBarLabel>)GetValue(LabelsProperty);
            set => SetValue(LabelsProperty, value);
        }

        #endregion

        #region LabelTemplate

        public static readonly DependencyProperty LabelTemplateProperty =
            DependencyProperty.Register(
                nameof(LabelTemplate),
                typeof(DataTemplate),
                typeof(AnnotatedScrollBar),
                new FrameworkPropertyMetadata(null, OnAnnotatedScrollBarPropertyChanged));

        public DataTemplate LabelTemplate
        {
            get => (DataTemplate)GetValue(LabelTemplateProperty);
            set => SetValue(LabelTemplateProperty, value);
        }

        #endregion

        #region DetailLabelTemplate

        public static readonly DependencyProperty DetailLabelTemplateProperty =
            DependencyProperty.Register(
                nameof(DetailLabelTemplate),
                typeof(DataTemplate),
                typeof(AnnotatedScrollBar),
                new FrameworkPropertyMetadata(null, OnAnnotatedScrollBarPropertyChanged));

        public DataTemplate DetailLabelTemplate
        {
            get => (DataTemplate)GetValue(DetailLabelTemplateProperty);
            set => SetValue(DetailLabelTemplateProperty, value);
        }

        #endregion

        #region SmallChange

        public static readonly DependencyProperty SmallChangeProperty =
            DependencyProperty.Register(
                nameof(SmallChange),
                typeof(double),
                typeof(AnnotatedScrollBar),
                new FrameworkPropertyMetadata(0d));

        public double SmallChange
        {
            get => (double)GetValue(SmallChangeProperty);
            set => SetValue(SmallChangeProperty, value);
        }

        #endregion
    }
}
