//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWpf.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernWpf.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, icon.
        /// </summary>
        internal static string BadgeIcon {
            get {
                return ResourceManager.GetString("BadgeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!s!.
        /// </summary>
        internal static string BadgeIconTextOverride {
            get {
                return ResourceManager.GetString("BadgeIconTextOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural1 {
            get {
                return ResourceManager.GetString("BadgeItemPlural1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural2 {
            get {
                return ResourceManager.GetString("BadgeItemPlural2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural3 {
            get {
                return ResourceManager.GetString("BadgeItemPlural3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural4 {
            get {
                return ResourceManager.GetString("BadgeItemPlural4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural5 {
            get {
                return ResourceManager.GetString("BadgeItemPlural5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural6 {
            get {
                return ResourceManager.GetString("BadgeItemPlural6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! items.
        /// </summary>
        internal static string BadgeItemPlural7 {
            get {
                return ResourceManager.GetString("BadgeItemPlural7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! item.
        /// </summary>
        internal static string BadgeItemSingular {
            get {
                return ResourceManager.GetString("BadgeItemSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %1!s!, %2!u! %3!s!.
        /// </summary>
        internal static string BadgeItemTextOverride {
            get {
                return ResourceManager.GetString("BadgeItemTextOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating, {0} of {1}.
        /// </summary>
        internal static string BasicRatingString {
            get {
                return ResourceManager.GetString("BasicRatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Rating, {0} of {1}.
        /// </summary>
        internal static string CommunityRatingString {
            get {
                return ResourceManager.GetString("CommunityRatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofing.
        /// </summary>
        internal static string ProofingMenuItemLabel {
            get {
                return ResourceManager.GetString("ProofingMenuItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RatingControlName {
            get {
                return ResourceManager.GetString("RatingControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Slider.
        /// </summary>
        internal static string RatingLocalizedControlType {
            get {
                return ResourceManager.GetString("RatingLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RatingsControlName {
            get {
                return ResourceManager.GetString("RatingsControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Unset.
        /// </summary>
        internal static string RatingUnset {
            get {
                return ResourceManager.GetString("RatingUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
    }
}
