// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls.Primitives
{
    internal partial class CommandBarFlyoutCommandBarTemplateSettingsProxy
    {
        #region FlyoutTemplateSettings

        public static readonly DependencyProperty FlyoutTemplateSettingsProperty =
            DependencyProperty.Register(
                nameof(FlyoutTemplateSettings),
                typeof(CommandBarFlyoutCommandBarTemplateSettings),
                typeof(CommandBarFlyoutCommandBarTemplateSettingsProxy),
                null);

        public CommandBarFlyoutCommandBarTemplateSettings FlyoutTemplateSettings
        {
            get => (CommandBarFlyoutCommandBarTemplateSettings)GetValue(FlyoutTemplateSettingsProperty);
            set => SetValue(FlyoutTemplateSettingsProperty, value);
        }

        #endregion
    }
}
