// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using System.Collections.ObjectModel;
using System.Windows;

namespace ModernWpf.Controls
{
    public partial class SelectorBar
    {
        #region Items

        private static readonly DependencyPropertyKey ItemsPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(Items),
                typeof(ObservableCollection<SelectorBarItem>),
                typeof(SelectorBar),
                new PropertyMetadata(null));

        public static readonly DependencyProperty ItemsProperty =
            ItemsPropertyKey.DependencyProperty;

        public ObservableCollection<SelectorBarItem> Items
        {
            get => (ObservableCollection<SelectorBarItem>)GetValue(ItemsProperty);
        }

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            ControlHelper.CornerRadiusProperty.AddOwner(typeof(SelectorBar));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion

        #region SelectedItem

        public static readonly DependencyProperty SelectedItemProperty =
            DependencyProperty.Register(
                nameof(SelectedItem),
                typeof(SelectorBarItem),
                typeof(SelectorBar),
                new FrameworkPropertyMetadata(null, OnSelectedItemPropertyChanged));

        public SelectorBarItem SelectedItem
        {
            get => (SelectorBarItem)GetValue(SelectedItemProperty);
            set => SetValue(SelectedItemProperty, value);
        }

        #endregion
    }
}
