// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace ModernWpf.Controls
{
    public partial class PagerControl
    {
        #region DisplayMode

        public static readonly DependencyProperty DisplayModeProperty =
            DependencyProperty.Register(
                nameof(DisplayMode),
                typeof(PagerControlDisplayMode),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(PagerControlDisplayMode.Auto, OnPagerPropertyChanged));

        public PagerControlDisplayMode DisplayMode
        {
            get => (PagerControlDisplayMode)GetValue(DisplayModeProperty);
            set => SetValue(DisplayModeProperty, value);
        }

        #endregion

        #region NumberOfPages

        public static readonly DependencyProperty NumberOfPagesProperty =
            DependencyProperty.Register(
                nameof(NumberOfPages),
                typeof(int),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(0, OnNumberOfPagesPropertyChanged, CoerceNumberOfPages));

        public int NumberOfPages
        {
            get => (int)GetValue(NumberOfPagesProperty);
            set => SetValue(NumberOfPagesProperty, value);
        }

        #endregion

        #region FirstButtonVisibility

        public static readonly DependencyProperty FirstButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(FirstButtonVisibility),
                typeof(PagerControlButtonVisibility),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(PagerControlButtonVisibility.Visible, OnPagerPropertyChanged));

        public PagerControlButtonVisibility FirstButtonVisibility
        {
            get => (PagerControlButtonVisibility)GetValue(FirstButtonVisibilityProperty);
            set => SetValue(FirstButtonVisibilityProperty, value);
        }

        #endregion

        #region PreviousButtonVisibility

        public static readonly DependencyProperty PreviousButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(PreviousButtonVisibility),
                typeof(PagerControlButtonVisibility),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(PagerControlButtonVisibility.Visible, OnPagerPropertyChanged));

        public PagerControlButtonVisibility PreviousButtonVisibility
        {
            get => (PagerControlButtonVisibility)GetValue(PreviousButtonVisibilityProperty);
            set => SetValue(PreviousButtonVisibilityProperty, value);
        }

        #endregion

        #region NextButtonVisibility

        public static readonly DependencyProperty NextButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(NextButtonVisibility),
                typeof(PagerControlButtonVisibility),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(PagerControlButtonVisibility.Visible, OnPagerPropertyChanged));

        public PagerControlButtonVisibility NextButtonVisibility
        {
            get => (PagerControlButtonVisibility)GetValue(NextButtonVisibilityProperty);
            set => SetValue(NextButtonVisibilityProperty, value);
        }

        #endregion

        #region LastButtonVisibility

        public static readonly DependencyProperty LastButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(LastButtonVisibility),
                typeof(PagerControlButtonVisibility),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(PagerControlButtonVisibility.Visible, OnPagerPropertyChanged));

        public PagerControlButtonVisibility LastButtonVisibility
        {
            get => (PagerControlButtonVisibility)GetValue(LastButtonVisibilityProperty);
            set => SetValue(LastButtonVisibilityProperty, value);
        }

        #endregion

        #region FirstButtonCommand

        public static readonly DependencyProperty FirstButtonCommandProperty =
            DependencyProperty.Register(
                nameof(FirstButtonCommand),
                typeof(ICommand),
                typeof(PagerControl),
                null);

        public ICommand FirstButtonCommand
        {
            get => (ICommand)GetValue(FirstButtonCommandProperty);
            set => SetValue(FirstButtonCommandProperty, value);
        }

        #endregion

        #region PreviousButtonCommand

        public static readonly DependencyProperty PreviousButtonCommandProperty =
            DependencyProperty.Register(
                nameof(PreviousButtonCommand),
                typeof(ICommand),
                typeof(PagerControl),
                null);

        public ICommand PreviousButtonCommand
        {
            get => (ICommand)GetValue(PreviousButtonCommandProperty);
            set => SetValue(PreviousButtonCommandProperty, value);
        }

        #endregion

        #region NextButtonCommand

        public static readonly DependencyProperty NextButtonCommandProperty =
            DependencyProperty.Register(
                nameof(NextButtonCommand),
                typeof(ICommand),
                typeof(PagerControl),
                null);

        public ICommand NextButtonCommand
        {
            get => (ICommand)GetValue(NextButtonCommandProperty);
            set => SetValue(NextButtonCommandProperty, value);
        }

        #endregion

        #region LastButtonCommand

        public static readonly DependencyProperty LastButtonCommandProperty =
            DependencyProperty.Register(
                nameof(LastButtonCommand),
                typeof(ICommand),
                typeof(PagerControl),
                null);

        public ICommand LastButtonCommand
        {
            get => (ICommand)GetValue(LastButtonCommandProperty);
            set => SetValue(LastButtonCommandProperty, value);
        }

        #endregion

        #region PagerInputCommand

        public static readonly DependencyProperty PagerInputCommandProperty =
            DependencyProperty.Register(
                nameof(PagerInputCommand),
                typeof(ICommand),
                typeof(PagerControl),
                null);

        public ICommand PagerInputCommand
        {
            get => (ICommand)GetValue(PagerInputCommandProperty);
            set => SetValue(PagerInputCommandProperty, value);
        }

        #endregion

        #region FirstButtonStyle

        public static readonly DependencyProperty FirstButtonStyleProperty =
            DependencyProperty.Register(
                nameof(FirstButtonStyle),
                typeof(Style),
                typeof(PagerControl),
                null);

        public Style FirstButtonStyle
        {
            get => (Style)GetValue(FirstButtonStyleProperty);
            set => SetValue(FirstButtonStyleProperty, value);
        }

        #endregion

        #region PreviousButtonStyle

        public static readonly DependencyProperty PreviousButtonStyleProperty =
            DependencyProperty.Register(
                nameof(PreviousButtonStyle),
                typeof(Style),
                typeof(PagerControl),
                null);

        public Style PreviousButtonStyle
        {
            get => (Style)GetValue(PreviousButtonStyleProperty);
            set => SetValue(PreviousButtonStyleProperty, value);
        }

        #endregion

        #region NextButtonStyle

        public static readonly DependencyProperty NextButtonStyleProperty =
            DependencyProperty.Register(
                nameof(NextButtonStyle),
                typeof(Style),
                typeof(PagerControl),
                null);

        public Style NextButtonStyle
        {
            get => (Style)GetValue(NextButtonStyleProperty);
            set => SetValue(NextButtonStyleProperty, value);
        }

        #endregion

        #region LastButtonStyle

        public static readonly DependencyProperty LastButtonStyleProperty =
            DependencyProperty.Register(
                nameof(LastButtonStyle),
                typeof(Style),
                typeof(PagerControl),
                null);

        public Style LastButtonStyle
        {
            get => (Style)GetValue(LastButtonStyleProperty);
            set => SetValue(LastButtonStyleProperty, value);
        }

        #endregion

        #region ButtonPanelAlwaysShowFirstLastPageIndex

        public static readonly DependencyProperty ButtonPanelAlwaysShowFirstLastPageIndexProperty =
            DependencyProperty.Register(
                nameof(ButtonPanelAlwaysShowFirstLastPageIndex),
                typeof(bool),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(true, OnPagerPropertyChanged));

        public bool ButtonPanelAlwaysShowFirstLastPageIndex
        {
            get => (bool)GetValue(ButtonPanelAlwaysShowFirstLastPageIndexProperty);
            set => SetValue(ButtonPanelAlwaysShowFirstLastPageIndexProperty, value);
        }

        #endregion

        #region SelectedPageIndex

        public static readonly DependencyProperty SelectedPageIndexProperty =
            DependencyProperty.Register(
                nameof(SelectedPageIndex),
                typeof(int),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(0, OnSelectedPageIndexPropertyChanged, CoerceSelectedPageIndex));

        public int SelectedPageIndex
        {
            get => (int)GetValue(SelectedPageIndexProperty);
            set => SetValue(SelectedPageIndexProperty, value);
        }

        #endregion

        #region PrefixText

        public static readonly DependencyProperty PrefixTextProperty =
            DependencyProperty.Register(
                nameof(PrefixText),
                typeof(string),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(string.Empty));

        public string PrefixText
        {
            get => (string)GetValue(PrefixTextProperty);
            set => SetValue(PrefixTextProperty, value);
        }

        #endregion

        #region SuffixText

        public static readonly DependencyProperty SuffixTextProperty =
            DependencyProperty.Register(
                nameof(SuffixText),
                typeof(string),
                typeof(PagerControl),
                new FrameworkPropertyMetadata(string.Empty));

        public string SuffixText
        {
            get => (string)GetValue(SuffixTextProperty);
            set => SetValue(SuffixTextProperty, value);
        }

        #endregion

        #region TemplateSettings

        private static readonly DependencyPropertyKey TemplateSettingsPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(TemplateSettings),
                typeof(PagerControlTemplateSettings),
                typeof(PagerControl),
                new PropertyMetadata(null));

        public static readonly DependencyProperty TemplateSettingsProperty =
            TemplateSettingsPropertyKey.DependencyProperty;

        public PagerControlTemplateSettings TemplateSettings
        {
            get => (PagerControlTemplateSettings)GetValue(TemplateSettingsProperty);
        }

        #endregion
    }
}
