// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class RefreshContainer
    {
        #region Visualizer

        public static readonly DependencyProperty VisualizerProperty =
            DependencyProperty.Register(
                nameof(Visualizer),
                typeof(RefreshVisualizer),
                typeof(RefreshContainer),
                new PropertyMetadata(null, OnVisualizerPropertyChanged));

        public RefreshVisualizer Visualizer
        {
            get => (RefreshVisualizer)GetValue(VisualizerProperty);
            set => SetValue(VisualizerProperty, value);
        }

        #endregion

        #region PullDirection

        public static readonly DependencyProperty PullDirectionProperty =
            DependencyProperty.Register(
                nameof(PullDirection),
                typeof(RefreshPullDirection),
                typeof(RefreshContainer),
                new PropertyMetadata(RefreshPullDirection.TopToBottom, OnPullDirectionPropertyChanged));

        public RefreshPullDirection PullDirection
        {
            get => (RefreshPullDirection)GetValue(PullDirectionProperty);
            set => SetValue(PullDirectionProperty, value);
        }

        #endregion
    }
}
