// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class RefreshVisualizer
    {
        #region State

        private static readonly DependencyPropertyKey StatePropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(State),
                typeof(RefreshVisualizerState),
                typeof(RefreshVisualizer),
                new PropertyMetadata(RefreshVisualizerState.Idle, OnStateChanged));

        public static readonly DependencyProperty StateProperty =
            StatePropertyKey.DependencyProperty;

        public RefreshVisualizerState State
        {
            get => (RefreshVisualizerState)GetValue(StateProperty);
        }

        #endregion

        #region InfoProvider

        public static readonly DependencyProperty InfoProviderProperty =
            DependencyProperty.Register(
                nameof(InfoProvider),
                typeof(object),
                typeof(RefreshVisualizer),
                new PropertyMetadata(null, OnInfoProviderChanged));

        #endregion

        #region Orientation

        public static readonly DependencyProperty OrientationProperty =
            DependencyProperty.Register(
                nameof(Orientation),
                typeof(RefreshVisualizerOrientation),
                typeof(RefreshVisualizer),
                new PropertyMetadata(RefreshVisualizerOrientation.Auto, OnOrientationChanged));

        public RefreshVisualizerOrientation Orientation
        {
            get => (RefreshVisualizerOrientation)GetValue(OrientationProperty);
            set => SetValue(OrientationProperty, value);
        }

        #endregion

        #region Content

        public static readonly DependencyProperty ContentProperty =
            DependencyProperty.Register(
                nameof(Content),
                typeof(UIElement),
                typeof(RefreshVisualizer),
                new PropertyMetadata(null, OnContentChanged));

        public UIElement Content
        {
            get => (UIElement)GetValue(ContentProperty);
            set => SetValue(ContentProperty, value);
        }

        #endregion
    }
}
