// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls.Primitives
{
    public partial class InfoBarPanel
    {
        #region HorizontalOrientationPadding

        public static readonly DependencyProperty HorizontalOrientationPaddingProperty =
            DependencyProperty.Register(
                nameof(HorizontalOrientationPadding),
                typeof(Thickness),
                typeof(InfoBarPanel),
                new FrameworkPropertyMetadata(default(Thickness), FrameworkPropertyMetadataOptions.AffectsMeasure));

        public Thickness HorizontalOrientationPadding
        {
            get => (Thickness)GetValue(HorizontalOrientationPaddingProperty);
            set => SetValue(HorizontalOrientationPaddingProperty, value);
        }

        #endregion

        #region VerticalOrientationPadding

        public static readonly DependencyProperty VerticalOrientationPaddingProperty =
            DependencyProperty.Register(
                nameof(VerticalOrientationPadding),
                typeof(Thickness),
                typeof(InfoBarPanel),
                new FrameworkPropertyMetadata(default(Thickness), FrameworkPropertyMetadataOptions.AffectsMeasure));

        public Thickness VerticalOrientationPadding
        {
            get => (Thickness)GetValue(VerticalOrientationPaddingProperty);
            set => SetValue(VerticalOrientationPaddingProperty, value);
        }

        #endregion

        #region HorizontalOrientationMargin

        public static readonly DependencyProperty HorizontalOrientationMarginProperty =
            DependencyProperty.RegisterAttached(
                "HorizontalOrientationMargin",
                typeof(Thickness),
                typeof(InfoBarPanel),
                new FrameworkPropertyMetadata(default(Thickness), FrameworkPropertyMetadataOptions.AffectsParentMeasure));

        public static Thickness GetHorizontalOrientationMargin(DependencyObject element)
        {
            return (Thickness)element.GetValue(HorizontalOrientationMarginProperty);
        }

        public static void SetHorizontalOrientationMargin(DependencyObject element, Thickness value)
        {
            element.SetValue(HorizontalOrientationMarginProperty, value);
        }

        #endregion

        #region VerticalOrientationMargin

        public static readonly DependencyProperty VerticalOrientationMarginProperty =
            DependencyProperty.RegisterAttached(
                "VerticalOrientationMargin",
                typeof(Thickness),
                typeof(InfoBarPanel),
                new FrameworkPropertyMetadata(default(Thickness), FrameworkPropertyMetadataOptions.AffectsParentMeasure));

        public static Thickness GetVerticalOrientationMargin(DependencyObject element)
        {
            return (Thickness)element.GetValue(VerticalOrientationMarginProperty);
        }

        public static void SetVerticalOrientationMargin(DependencyObject element, Thickness value)
        {
            element.SetValue(VerticalOrientationMarginProperty, value);
        }

        #endregion
    }
}
