// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class PipsPager
    {
        #region NumberOfPages

        public static readonly DependencyProperty NumberOfPagesProperty =
            DependencyProperty.Register(
                nameof(NumberOfPages),
                typeof(int),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(-1, OnPagerPropertyChanged, CoerceNumberOfPages));

        public int NumberOfPages
        {
            get => (int)GetValue(NumberOfPagesProperty);
            set => SetValue(NumberOfPagesProperty, value);
        }

        #endregion

        #region SelectedPageIndex

        public static readonly DependencyProperty SelectedPageIndexProperty =
            DependencyProperty.Register(
                nameof(SelectedPageIndex),
                typeof(int),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(0, OnSelectedPageIndexPropertyChanged, CoerceSelectedPageIndex));

        public int SelectedPageIndex
        {
            get => (int)GetValue(SelectedPageIndexProperty);
            set => SetValue(SelectedPageIndexProperty, value);
        }

        #endregion

        #region MaxVisiblePips

        public static readonly DependencyProperty MaxVisiblePipsProperty =
            DependencyProperty.Register(
                nameof(MaxVisiblePips),
                typeof(int),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(5, OnPagerPropertyChanged, CoerceNonNegativeInt));

        public int MaxVisiblePips
        {
            get => (int)GetValue(MaxVisiblePipsProperty);
            set => SetValue(MaxVisiblePipsProperty, value);
        }

        #endregion

        #region Orientation

        public static readonly DependencyProperty OrientationProperty =
            DependencyProperty.Register(
                nameof(Orientation),
                typeof(Orientation),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(Orientation.Horizontal, OnPagerPropertyChanged));

        public Orientation Orientation
        {
            get => (Orientation)GetValue(OrientationProperty);
            set => SetValue(OrientationProperty, value);
        }

        #endregion

        #region PreviousButtonVisibility

        public static readonly DependencyProperty PreviousButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(PreviousButtonVisibility),
                typeof(PipsPagerButtonVisibility),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(PipsPagerButtonVisibility.Collapsed, OnPagerPropertyChanged));

        public PipsPagerButtonVisibility PreviousButtonVisibility
        {
            get => (PipsPagerButtonVisibility)GetValue(PreviousButtonVisibilityProperty);
            set => SetValue(PreviousButtonVisibilityProperty, value);
        }

        #endregion

        #region NextButtonVisibility

        public static readonly DependencyProperty NextButtonVisibilityProperty =
            DependencyProperty.Register(
                nameof(NextButtonVisibility),
                typeof(PipsPagerButtonVisibility),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(PipsPagerButtonVisibility.Collapsed, OnPagerPropertyChanged));

        public PipsPagerButtonVisibility NextButtonVisibility
        {
            get => (PipsPagerButtonVisibility)GetValue(NextButtonVisibilityProperty);
            set => SetValue(NextButtonVisibilityProperty, value);
        }

        #endregion

        #region PreviousButtonStyle

        public static readonly DependencyProperty PreviousButtonStyleProperty =
            DependencyProperty.Register(
                nameof(PreviousButtonStyle),
                typeof(Style),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(null, OnPagerPropertyChanged));

        public Style PreviousButtonStyle
        {
            get => (Style)GetValue(PreviousButtonStyleProperty);
            set => SetValue(PreviousButtonStyleProperty, value);
        }

        #endregion

        #region NextButtonStyle

        public static readonly DependencyProperty NextButtonStyleProperty =
            DependencyProperty.Register(
                nameof(NextButtonStyle),
                typeof(Style),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(null, OnPagerPropertyChanged));

        public Style NextButtonStyle
        {
            get => (Style)GetValue(NextButtonStyleProperty);
            set => SetValue(NextButtonStyleProperty, value);
        }

        #endregion

        #region SelectedPipStyle

        public static readonly DependencyProperty SelectedPipStyleProperty =
            DependencyProperty.Register(
                nameof(SelectedPipStyle),
                typeof(Style),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(null, OnPagerPropertyChanged));

        public Style SelectedPipStyle
        {
            get => (Style)GetValue(SelectedPipStyleProperty);
            set => SetValue(SelectedPipStyleProperty, value);
        }

        #endregion

        #region NormalPipStyle

        public static readonly DependencyProperty NormalPipStyleProperty =
            DependencyProperty.Register(
                nameof(NormalPipStyle),
                typeof(Style),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(null, OnPagerPropertyChanged));

        public Style NormalPipStyle
        {
            get => (Style)GetValue(NormalPipStyleProperty);
            set => SetValue(NormalPipStyleProperty, value);
        }

        #endregion

        #region WrapMode

        public static readonly DependencyProperty WrapModeProperty =
            DependencyProperty.Register(
                nameof(WrapMode),
                typeof(PipsPagerWrapMode),
                typeof(PipsPager),
                new FrameworkPropertyMetadata(PipsPagerWrapMode.None, OnPagerPropertyChanged));

        public PipsPagerWrapMode WrapMode
        {
            get => (PipsPagerWrapMode)GetValue(WrapModeProperty);
            set => SetValue(WrapModeProperty, value);
        }

        #endregion

        #region TemplateSettings

        private static readonly DependencyPropertyKey TemplateSettingsPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(TemplateSettings),
                typeof(PipsPagerTemplateSettings),
                typeof(PipsPager),
                new PropertyMetadata(null));

        public static readonly DependencyProperty TemplateSettingsProperty =
            TemplateSettingsPropertyKey.DependencyProperty;

        public PipsPagerTemplateSettings TemplateSettings
        {
            get => (PipsPagerTemplateSettings)GetValue(TemplateSettingsProperty);
        }

        #endregion
    }
}
