// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using ModernWpf.Media.Animation;
using System.Windows;

namespace ModernWpf.Controls
{
    public partial class SwipeControl
    {
        #region ContentTransitions

        public static readonly DependencyProperty ContentTransitionsProperty =
            ControlHelper.ContentTransitionsProperty.AddOwner(typeof(SwipeControl));

        public TransitionCollection ContentTransitions
        {
            get => (TransitionCollection)GetValue(ContentTransitionsProperty);
            set => SetValue(ContentTransitionsProperty, value);
        }

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            System.Windows.Controls.Border.CornerRadiusProperty.AddOwner(typeof(SwipeControl));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion

        #region LeftItems

        public static readonly DependencyProperty LeftItemsProperty =
            DependencyProperty.Register(
                nameof(LeftItems),
                typeof(SwipeItems),
                typeof(SwipeControl),
                new FrameworkPropertyMetadata(null, OnItemsPropertyChanged));

        public SwipeItems LeftItems
        {
            get => (SwipeItems)GetValue(LeftItemsProperty);
            set
            {
                ValidateSwipeItemsCanSet(value, SwipeItemsPlacement.Left);
                SetValue(LeftItemsProperty, value);
            }
        }

        #endregion

        #region RightItems

        public static readonly DependencyProperty RightItemsProperty =
            DependencyProperty.Register(
                nameof(RightItems),
                typeof(SwipeItems),
                typeof(SwipeControl),
                new FrameworkPropertyMetadata(null, OnItemsPropertyChanged));

        public SwipeItems RightItems
        {
            get => (SwipeItems)GetValue(RightItemsProperty);
            set
            {
                ValidateSwipeItemsCanSet(value, SwipeItemsPlacement.Right);
                SetValue(RightItemsProperty, value);
            }
        }

        #endregion

        #region TopItems

        public static readonly DependencyProperty TopItemsProperty =
            DependencyProperty.Register(
                nameof(TopItems),
                typeof(SwipeItems),
                typeof(SwipeControl),
                new FrameworkPropertyMetadata(null, OnItemsPropertyChanged));

        public SwipeItems TopItems
        {
            get => (SwipeItems)GetValue(TopItemsProperty);
            set
            {
                ValidateSwipeItemsCanSet(value, SwipeItemsPlacement.Top);
                SetValue(TopItemsProperty, value);
            }
        }

        #endregion

        #region BottomItems

        public static readonly DependencyProperty BottomItemsProperty =
            DependencyProperty.Register(
                nameof(BottomItems),
                typeof(SwipeItems),
                typeof(SwipeControl),
                new FrameworkPropertyMetadata(null, OnItemsPropertyChanged));

        public SwipeItems BottomItems
        {
            get => (SwipeItems)GetValue(BottomItemsProperty);
            set
            {
                ValidateSwipeItemsCanSet(value, SwipeItemsPlacement.Bottom);
                SetValue(BottomItemsProperty, value);
            }
        }

        #endregion
    }
}
