// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class TeachingTipTemplateSettings
    {
        #region TopRightHighlightMargin

        public static readonly DependencyProperty TopRightHighlightMarginProperty =
            DependencyProperty.Register(
                nameof(TopRightHighlightMargin),
                typeof(Thickness),
                typeof(TeachingTipTemplateSettings),
                new PropertyMetadata(new Thickness()));

        public Thickness TopRightHighlightMargin
        {
            get => (Thickness)GetValue(TopRightHighlightMarginProperty);
            internal set => SetValue(TopRightHighlightMarginProperty, value);
        }

        #endregion

        #region TopLeftHighlightMargin

        public static readonly DependencyProperty TopLeftHighlightMarginProperty =
            DependencyProperty.Register(
                nameof(TopLeftHighlightMargin),
                typeof(Thickness),
                typeof(TeachingTipTemplateSettings),
                new PropertyMetadata(new Thickness()));

        public Thickness TopLeftHighlightMargin
        {
            get => (Thickness)GetValue(TopLeftHighlightMarginProperty);
            internal set => SetValue(TopLeftHighlightMarginProperty, value);
        }

        #endregion

        #region IconElement

        public static readonly DependencyProperty IconElementProperty =
            DependencyProperty.Register(
                nameof(IconElement),
                typeof(IconElement),
                typeof(TeachingTipTemplateSettings),
                null);

        public IconElement IconElement
        {
            get => (IconElement)GetValue(IconElementProperty);
            internal set => SetValue(IconElementProperty, value);
        }

        #endregion
    }
}
