// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace ModernWpf.Controls
{
    public partial class TeachingTip
    {
        #region Title

        public static readonly DependencyProperty TitleProperty =
            DependencyProperty.Register(
                nameof(Title),
                typeof(string),
                typeof(TeachingTip),
                new PropertyMetadata(string.Empty, OnVisualStatePropertyChanged));

        public string Title
        {
            get => (string)GetValue(TitleProperty);
            set => SetValue(TitleProperty, value);
        }

        #endregion

        #region Subtitle

        public static readonly DependencyProperty SubtitleProperty =
            DependencyProperty.Register(
                nameof(Subtitle),
                typeof(string),
                typeof(TeachingTip),
                new PropertyMetadata(string.Empty, OnVisualStatePropertyChanged));

        public string Subtitle
        {
            get => (string)GetValue(SubtitleProperty);
            set => SetValue(SubtitleProperty, value);
        }

        #endregion

        #region IsOpen

        public static readonly DependencyProperty IsOpenProperty =
            DependencyProperty.Register(
                nameof(IsOpen),
                typeof(bool),
                typeof(TeachingTip),
                new PropertyMetadata(false, OnIsOpenPropertyChanged));

        public bool IsOpen
        {
            get => (bool)GetValue(IsOpenProperty);
            set => SetValue(IsOpenProperty, value);
        }

        #endregion

        #region Target

        public static readonly DependencyProperty TargetProperty =
            DependencyProperty.Register(
                nameof(Target),
                typeof(FrameworkElement),
                typeof(TeachingTip),
                new PropertyMetadata(null, OnTargetPropertyChanged));

        public FrameworkElement Target
        {
            get => (FrameworkElement)GetValue(TargetProperty);
            set => SetValue(TargetProperty, value);
        }

        #endregion

        #region TailVisibility

        public static readonly DependencyProperty TailVisibilityProperty =
            DependencyProperty.Register(
                nameof(TailVisibility),
                typeof(TeachingTipTailVisibility),
                typeof(TeachingTip),
                new PropertyMetadata(TeachingTipTailVisibility.Auto, OnVisualStatePropertyChanged));

        public TeachingTipTailVisibility TailVisibility
        {
            get => (TeachingTipTailVisibility)GetValue(TailVisibilityProperty);
            set => SetValue(TailVisibilityProperty, value);
        }

        #endregion

        #region ActionButtonContent

        public static readonly DependencyProperty ActionButtonContentProperty =
            DependencyProperty.Register(
                nameof(ActionButtonContent),
                typeof(object),
                typeof(TeachingTip),
                new PropertyMetadata(null, OnVisualStatePropertyChanged));

        public object ActionButtonContent
        {
            get => (object)GetValue(ActionButtonContentProperty);
            set => SetValue(ActionButtonContentProperty, value);
        }

        #endregion

        #region ActionButtonStyle

        public static readonly DependencyProperty ActionButtonStyleProperty =
            DependencyProperty.Register(
                nameof(ActionButtonStyle),
                typeof(Style),
                typeof(TeachingTip),
                null);

        public Style ActionButtonStyle
        {
            get => (Style)GetValue(ActionButtonStyleProperty);
            set => SetValue(ActionButtonStyleProperty, value);
        }

        #endregion

        #region ActionButtonCommand

        public static readonly DependencyProperty ActionButtonCommandProperty =
            DependencyProperty.Register(
                nameof(ActionButtonCommand),
                typeof(ICommand),
                typeof(TeachingTip),
                null);

        public ICommand ActionButtonCommand
        {
            get => (ICommand)GetValue(ActionButtonCommandProperty);
            set => SetValue(ActionButtonCommandProperty, value);
        }

        #endregion

        #region ActionButtonCommandParameter

        public static readonly DependencyProperty ActionButtonCommandParameterProperty =
            DependencyProperty.Register(
                nameof(ActionButtonCommandParameter),
                typeof(object),
                typeof(TeachingTip),
                null);

        public object ActionButtonCommandParameter
        {
            get => (object)GetValue(ActionButtonCommandParameterProperty);
            set => SetValue(ActionButtonCommandParameterProperty, value);
        }

        #endregion

        #region CloseButtonContent

        public static readonly DependencyProperty CloseButtonContentProperty =
            DependencyProperty.Register(
                nameof(CloseButtonContent),
                typeof(object),
                typeof(TeachingTip),
                new PropertyMetadata(null, OnVisualStatePropertyChanged));

        public object CloseButtonContent
        {
            get => (object)GetValue(CloseButtonContentProperty);
            set => SetValue(CloseButtonContentProperty, value);
        }

        #endregion

        #region CloseButtonStyle

        public static readonly DependencyProperty CloseButtonStyleProperty =
            DependencyProperty.Register(
                nameof(CloseButtonStyle),
                typeof(Style),
                typeof(TeachingTip),
                null);

        public Style CloseButtonStyle
        {
            get => (Style)GetValue(CloseButtonStyleProperty);
            set => SetValue(CloseButtonStyleProperty, value);
        }

        #endregion

        #region CloseButtonCommand

        public static readonly DependencyProperty CloseButtonCommandProperty =
            DependencyProperty.Register(
                nameof(CloseButtonCommand),
                typeof(ICommand),
                typeof(TeachingTip),
                null);

        public ICommand CloseButtonCommand
        {
            get => (ICommand)GetValue(CloseButtonCommandProperty);
            set => SetValue(CloseButtonCommandProperty, value);
        }

        #endregion

        #region CloseButtonCommandParameter

        public static readonly DependencyProperty CloseButtonCommandParameterProperty =
            DependencyProperty.Register(
                nameof(CloseButtonCommandParameter),
                typeof(object),
                typeof(TeachingTip),
                null);

        public object CloseButtonCommandParameter
        {
            get => (object)GetValue(CloseButtonCommandParameterProperty);
            set => SetValue(CloseButtonCommandParameterProperty, value);
        }

        #endregion

        #region PlacementMargin

        public static readonly DependencyProperty PlacementMarginProperty =
            DependencyProperty.Register(
                nameof(PlacementMargin),
                typeof(Thickness),
                typeof(TeachingTip),
                new PropertyMetadata(new Thickness(), OnVisualStatePropertyChanged));

        public Thickness PlacementMargin
        {
            get => (Thickness)GetValue(PlacementMarginProperty);
            set => SetValue(PlacementMarginProperty, value);
        }

        #endregion

        #region ShouldConstrainToRootBounds

        public static readonly DependencyProperty ShouldConstrainToRootBoundsProperty =
            DependencyProperty.Register(
                nameof(ShouldConstrainToRootBounds),
                typeof(bool),
                typeof(TeachingTip),
                new PropertyMetadata(true, OnVisualStatePropertyChanged));

        public bool ShouldConstrainToRootBounds
        {
            get => (bool)GetValue(ShouldConstrainToRootBoundsProperty);
            set => SetValue(ShouldConstrainToRootBoundsProperty, value);
        }

        #endregion

        #region IsLightDismissEnabled

        public static readonly DependencyProperty IsLightDismissEnabledProperty =
            DependencyProperty.Register(
                nameof(IsLightDismissEnabled),
                typeof(bool),
                typeof(TeachingTip),
                new PropertyMetadata(false, OnVisualStatePropertyChanged));

        public bool IsLightDismissEnabled
        {
            get => (bool)GetValue(IsLightDismissEnabledProperty);
            set => SetValue(IsLightDismissEnabledProperty, value);
        }

        #endregion

        #region PreferredPlacement

        public static readonly DependencyProperty PreferredPlacementProperty =
            DependencyProperty.Register(
                nameof(PreferredPlacement),
                typeof(TeachingTipPlacementMode),
                typeof(TeachingTip),
                new PropertyMetadata(TeachingTipPlacementMode.Auto, OnVisualStatePropertyChanged));

        public TeachingTipPlacementMode PreferredPlacement
        {
            get => (TeachingTipPlacementMode)GetValue(PreferredPlacementProperty);
            set => SetValue(PreferredPlacementProperty, value);
        }

        #endregion

        #region HeroContentPlacement

        public static readonly DependencyProperty HeroContentPlacementProperty =
            DependencyProperty.Register(
                nameof(HeroContentPlacement),
                typeof(TeachingTipHeroContentPlacementMode),
                typeof(TeachingTip),
                new PropertyMetadata(TeachingTipHeroContentPlacementMode.Auto, OnVisualStatePropertyChanged));

        public TeachingTipHeroContentPlacementMode HeroContentPlacement
        {
            get => (TeachingTipHeroContentPlacementMode)GetValue(HeroContentPlacementProperty);
            set => SetValue(HeroContentPlacementProperty, value);
        }

        #endregion

        #region HeroContent

        public static readonly DependencyProperty HeroContentProperty =
            DependencyProperty.Register(
                nameof(HeroContent),
                typeof(UIElement),
                typeof(TeachingTip),
                new PropertyMetadata(null, OnVisualStatePropertyChanged));

        public UIElement HeroContent
        {
            get => (UIElement)GetValue(HeroContentProperty);
            set => SetValue(HeroContentProperty, value);
        }

        #endregion

        #region IconSource

        public static readonly DependencyProperty IconSourceProperty =
            DependencyProperty.Register(
                nameof(IconSource),
                typeof(IconSource),
                typeof(TeachingTip),
                new PropertyMetadata(null, OnIconSourcePropertyChanged));

        public IconSource IconSource
        {
            get => (IconSource)GetValue(IconSourceProperty);
            set => SetValue(IconSourceProperty, value);
        }

        #endregion

        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            Border.CornerRadiusProperty.AddOwner(
                typeof(TeachingTip),
                new FrameworkPropertyMetadata(new CornerRadius()));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion

        #region TemplateSettings

        private static readonly DependencyPropertyKey TemplateSettingsPropertyKey =
            DependencyProperty.RegisterReadOnly(
                nameof(TemplateSettings),
                typeof(TeachingTipTemplateSettings),
                typeof(TeachingTip),
                new PropertyMetadata(null));

        public static readonly DependencyProperty TemplateSettingsProperty =
            TemplateSettingsPropertyKey.DependencyProperty;

        public TeachingTipTemplateSettings TemplateSettings
        {
            get => (TeachingTipTemplateSettings)GetValue(TemplateSettingsProperty);
        }

        #endregion
    }
}
