// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    public partial class AppBarSeparator
    {
        #region IsCompact

        public static readonly DependencyProperty IsCompactProperty =
            AppBarElementProperties.IsCompactProperty.AddOwner(typeof(AppBarSeparator));

        public bool IsCompact
        {
            get => (bool)GetValue(IsCompactProperty);
            set => SetValue(IsCompactProperty, value);
        }

        #endregion

        #region IsInOverflow

        public static readonly DependencyProperty IsInOverflowProperty =
            AppBarElementProperties.IsInOverflowProperty.AddOwner(typeof(AppBarSeparator));

        public bool IsInOverflow
        {
            get => (bool)GetValue(IsInOverflowProperty);
        }

        #endregion

        #region DynamicOverflowOrder

        public static readonly DependencyProperty DynamicOverflowOrderProperty =
            AppBarElementProperties.DynamicOverflowOrderProperty.AddOwner(typeof(AppBarSeparator));

        public int DynamicOverflowOrder
        {
            get => (int)GetValue(DynamicOverflowOrderProperty);
            set => SetValue(DynamicOverflowOrderProperty, value);
        }

        #endregion
    }
}
