// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls
{
    internal static partial class AppBarElementProperties
    {
        #region Icon

        public static readonly DependencyProperty IconProperty =
            DependencyProperty.RegisterAttached(
                "Icon",
                typeof(IconElement),
                typeof(AppBarElementProperties),
                new PropertyMetadata(OnIconChanged));

        #endregion

        #region Label

        public static readonly DependencyProperty LabelProperty =
            DependencyProperty.RegisterAttached(
                "Label",
                typeof(string),
                typeof(AppBarElementProperties),
                new PropertyMetadata(string.Empty, OnLabelChanged, CoerceLabel));

        #endregion

        #region DefaultLabelPosition

        internal static readonly DependencyProperty DefaultLabelPositionProperty =
            DependencyProperty.RegisterAttached(
                "DefaultLabelPosition",
                typeof(CommandBarDefaultLabelPosition),
                typeof(AppBarElementProperties),
                new PropertyMetadata(CommandBarDefaultLabelPosition.Bottom, OnDefaultLabelPositionChanged));

        #endregion

        #region LabelPosition

        public static readonly DependencyProperty LabelPositionProperty =
            DependencyProperty.RegisterAttached(
                "LabelPosition",
                typeof(CommandBarLabelPosition),
                typeof(AppBarElementProperties),
                new PropertyMetadata(CommandBarLabelPosition.Default, OnLabelPositionChanged));

        #endregion

        #region IsCompact

        public static readonly DependencyProperty IsCompactProperty =
            DependencyProperty.RegisterAttached(
                "IsCompact",
                typeof(bool),
                typeof(AppBarElementProperties),
                new PropertyMetadata(false, OnIsCompactChanged));

        #endregion

        #region UseOverflowStyle

        internal static readonly DependencyProperty UseOverflowStyleProperty =
            DependencyProperty.RegisterAttached(
                "UseOverflowStyle",
                typeof(bool),
                typeof(AppBarElementProperties),
                new PropertyMetadata(false, OnUseOverflowStyleChanged));

        #endregion

        #region IsInOverflow

        internal static readonly DependencyPropertyKey IsInOverflowPropertyKey =
            DependencyProperty.RegisterAttachedReadOnly(
                "IsInOverflow",
                typeof(bool),
                typeof(AppBarElementProperties),
                new PropertyMetadata(false, OnIsInOverflowChanged));

        public static readonly DependencyProperty IsInOverflowProperty =
            IsInOverflowPropertyKey.DependencyProperty;

        #endregion

        #region KeyboardAcceleratorTextOverride

        public static readonly DependencyProperty KeyboardAcceleratorTextOverrideProperty =
            DependencyProperty.RegisterAttached(
                "KeyboardAcceleratorTextOverride",
                typeof(string),
                typeof(AppBarElementProperties),
                new PropertyMetadata(string.Empty, OnInputGestureTextChanged, CoerceInputGestureText));

        #endregion

        #region HasInputGestureText

        private static readonly DependencyPropertyKey HasInputGestureTextPropertyKey =
            DependencyProperty.RegisterAttachedReadOnly(
                "HasInputGestureText",
                typeof(bool),
                typeof(AppBarElementProperties),
                new PropertyMetadata(false, OnHasInputGestureTextChanged));

        public static readonly DependencyProperty HasInputGestureTextProperty =
            HasInputGestureTextPropertyKey.DependencyProperty;

        #endregion

        #region ShowKeyboardAcceleratorText

        internal static readonly DependencyProperty ShowKeyboardAcceleratorTextProperty =
            DependencyProperty.RegisterAttached(
                "ShowKeyboardAcceleratorText",
                typeof(bool),
                typeof(AppBarElementProperties),
                null);

        #endregion
    }
}
