// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;

namespace ModernWpf.Controls.Primitives
{
    public sealed partial class AppBarToggleButtonTemplateSettings
    {
        #region KeyboardAcceleratorTextMinWidth

        public static readonly DependencyProperty KeyboardAcceleratorTextMinWidthProperty =
            DependencyProperty.Register(
                nameof(KeyboardAcceleratorTextMinWidth),
                typeof(double),
                typeof(AppBarToggleButtonTemplateSettings),
                new PropertyMetadata(0.0));

        public double KeyboardAcceleratorTextMinWidth
        {
            get => (double)GetValue(KeyboardAcceleratorTextMinWidthProperty);
            internal set => SetValue(KeyboardAcceleratorTextMinWidthProperty, value);
        }

        #endregion
    }
}
