// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls.Primitives;
using ModernWpf.Media.Animation;
using System.Windows;

namespace ModernWpf.Controls
{
    public partial class AppBarElementContainer
    {
        #region ContentTransitions

        public static readonly DependencyProperty ContentTransitionsProperty =
            ControlHelper.ContentTransitionsProperty.AddOwner(typeof(AppBarElementContainer));

        public TransitionCollection ContentTransitions
        {
            get => (TransitionCollection)GetValue(ContentTransitionsProperty);
            set => SetValue(ContentTransitionsProperty, value);
        }

        #endregion

        #region IsCompact

        public static readonly DependencyProperty IsCompactProperty =
            AppBarElementProperties.IsCompactProperty.AddOwner(typeof(AppBarElementContainer));

        public bool IsCompact
        {
            get => (bool)GetValue(IsCompactProperty);
            set => SetValue(IsCompactProperty, value);
        }

        #endregion

        #region IsInOverflow

        public static readonly DependencyProperty IsInOverflowProperty =
            AppBarElementProperties.IsInOverflowProperty.AddOwner(typeof(AppBarElementContainer));

        public bool IsInOverflow
        {
            get => (bool)GetValue(IsInOverflowProperty);
        }

        #endregion

        #region DynamicOverflowOrder

        public static readonly DependencyProperty DynamicOverflowOrderProperty =
            AppBarElementProperties.DynamicOverflowOrderProperty.AddOwner(typeof(AppBarElementContainer));

        public int DynamicOverflowOrder
        {
            get => (int)GetValue(DynamicOverflowOrderProperty);
            set => SetValue(DynamicOverflowOrderProperty, value);
        }

        #endregion
    }
}
