// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using ModernWpf.Controls;
using System.Windows;

namespace ModernWpf.Controls.Primitives
{
    public partial class CommandBarOverflowPresenter
    {
        #region CornerRadius

        public static readonly DependencyProperty CornerRadiusProperty =
            System.Windows.Controls.Border.CornerRadiusProperty.AddOwner(typeof(CommandBarOverflowPresenter));

        public CornerRadius CornerRadius
        {
            get => (CornerRadius)GetValue(CornerRadiusProperty);
            set => SetValue(CornerRadiusProperty, value);
        }

        #endregion
    }
}
