//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWpf.SampleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernWpf.SampleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Controls by function 的本地化字符串。
        /// </summary>
        public static string ByFunctionHeader_Text {
            get {
                return ResourceManager.GetString("ByFunctionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls by name 的本地化字符串。
        /// </summary>
        public static string ByNameHeader_Text {
            get {
                return ResourceManager.GetString("ByNameHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documentation 的本地化字符串。
        /// </summary>
        public static string DocHeader_Text {
            get {
                return ResourceManager.GetString("DocHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string FeedbackHeader_Text {
            get {
                return ResourceManager.GetString("FeedbackHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send feedback about this page 的本地化字符串。
        /// </summary>
        public static string FeedbackLink_Text {
            get {
                return ResourceManager.GetString("FeedbackLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From any control page, open the help panel from the bottom app bar to see custom help content for that control. 的本地化字符串。
        /// </summary>
        public static string helpFlyoutContent {
            get {
                return ResourceManager.GetString("helpFlyoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string helpFlyoutLabel {
            get {
                return ResourceManager.GetString("helpFlyoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/body&gt;&lt;/html&gt; 的本地化字符串。
        /// </summary>
        public static string HTMLCloseTags {
            get {
                return ResourceManager.GetString("HTMLCloseTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;style&gt;body {font-family: &apos;Segoe UI&apos;;}&lt;/style&gt;&lt;/head&gt;&lt;body&gt; 的本地化字符串。
        /// </summary>
        public static string HTMLOpenTags {
            get {
                return ResourceManager.GetString("HTMLOpenTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModernWpf.SampleApp.ControlPages. 的本地化字符串。
        /// </summary>
        public static string PageStringRoot {
            get {
                return ResourceManager.GetString("PageStringRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Related controls 的本地化字符串。
        /// </summary>
        public static string RelatedControlsHeader_Text {
            get {
                return ResourceManager.GetString("RelatedControlsHeader.Text", resourceCulture);
            }
        }
    }
}
