name: Label issues
on:
  issues:
    types: [opened]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: andymckay/labeler@master
        with:
          add-labels: "needs-triage"
