// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />

using System.Windows;
using System.Windows.Controls;

namespace ModernWpf.Controls
{
    public partial class FlowLayout
    {
        #region LineAlignment

        public static readonly DependencyProperty LineAlignmentProperty =
            DependencyProperty.Register(
                nameof(LineAlignment),
                typeof(FlowLayoutLineAlignment),
                typeof(FlowLayout),
                new PropertyMetadata(FlowLayoutLineAlignment.Start, OnPropertyChanged));

        public FlowLayoutLineAlignment LineAlignment
        {
            get => (FlowLayoutLineAlignment)GetValue(LineAlignmentProperty);
            set => SetValue(LineAlignmentProperty, value);
        }

        #endregion

        #region LineSpacing

        public static readonly DependencyProperty LineSpacingProperty =
            DependencyProperty.Register(
                nameof(LineSpacing),
                typeof(double),
                typeof(FlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double LineSpacing
        {
            get => (double)GetValue(LineSpacingProperty);
            set => SetValue(LineSpacingProperty, value);
        }

        #endregion

        #region MinItemSpacing

        public static readonly DependencyProperty MinItemSpacingProperty =
            DependencyProperty.Register(
                nameof(MinItemSpacing),
                typeof(double),
                typeof(FlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double MinItemSpacing
        {
            get => (double)GetValue(MinItemSpacingProperty);
            set => SetValue(MinItemSpacingProperty, value);
        }

        #endregion

        #region MinColumnSpacing

        public static readonly DependencyProperty MinColumnSpacingProperty =
            DependencyProperty.Register(
                nameof(MinColumnSpacing),
                typeof(double),
                typeof(FlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double MinColumnSpacing
        {
            get => (double)GetValue(MinColumnSpacingProperty);
            set => SetValue(MinColumnSpacingProperty, value);
        }

        #endregion

        #region MinRowSpacing

        public static readonly DependencyProperty MinRowSpacingProperty =
            DependencyProperty.Register(
                nameof(MinRowSpacing),
                typeof(double),
                typeof(FlowLayout),
                new PropertyMetadata(0.0, OnPropertyChanged));

        public double MinRowSpacing
        {
            get => (double)GetValue(MinRowSpacingProperty);
            set => SetValue(MinRowSpacingProperty, value);
        }

        #endregion

        #region Orientation

        public static readonly DependencyProperty OrientationProperty =
            DependencyProperty.Register(
                nameof(Orientation),
                typeof(Orientation),
                typeof(FlowLayout),
                new PropertyMetadata(Orientation.Horizontal, OnPropertyChanged));

        public Orientation Orientation
        {
            get => (Orientation)GetValue(OrientationProperty);
            set => SetValue(OrientationProperty, value);
        }

        #endregion
    }
}
