//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWpf.MahApps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernWpf.MahApps.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NavigationBackButtonName {
            get {
                return ResourceManager.GetString("NavigationBackButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string NavigationBackButtonToolTip {
            get {
                return ResourceManager.GetString("NavigationBackButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Navigation.
        /// </summary>
        internal static string NavigationButtonClosedName {
            get {
                return ResourceManager.GetString("NavigationButtonClosedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Navigation.
        /// </summary>
        internal static string NavigationButtonOpenName {
            get {
                return ResourceManager.GetString("NavigationButtonOpenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NavigationCloseButtonName {
            get {
                return ResourceManager.GetString("NavigationCloseButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Button.
        /// </summary>
        internal static string NavigationOverflowButtonName {
            get {
                return ResourceManager.GetString("NavigationOverflowButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string NavigationOverflowButtonText {
            get {
                return ResourceManager.GetString("NavigationOverflowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationViewItem.
        /// </summary>
        internal static string NavigationViewItemDefaultControlName {
            get {
                return ResourceManager.GetString("NavigationViewItemDefaultControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to search.
        /// </summary>
        internal static string NavigationViewSearchButtonName {
            get {
                return ResourceManager.GetString("NavigationViewSearchButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsButtonName {
            get {
                return ResourceManager.GetString("SettingsButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string TimePickerAM {
            get {
                return ResourceManager.GetString("TimePickerAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string TimePickerHour {
            get {
                return ResourceManager.GetString("TimePickerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string TimePickerMinute {
            get {
                return ResourceManager.GetString("TimePickerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string TimePickerSecond {
            get {
                return ResourceManager.GetString("TimePickerSecond", resourceCulture);
            }
        }
    }
}
